version: "3.8"
services:
  ratings:
    build: .
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2 #v1 work standalone without database
      MONGO_DB_URL: mongodb://ratings:SECUREPASS@mongodb:27017/ratings
  mongodb:
    image: bitnami/mongodb:4.4.1-debian-10-r12
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
    environment:
      MONGODB_ROOT_PASSWORD: SECUREROOTPASS
      MONGODB_USERNAME: ratings
      MONGODB_PASSWORD: SECUREPASS
      MONGODB_DATABASE: ratings
