apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.ratings.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.ratings.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.ratings.image }}:{{ .Values.ratings.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.ratings.port }}
              name: web-port
              protocol: TCP
        {{- if .Values.extraEnv }}
          env:
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
        {{- end }}
          resources:
            requests:
              cpu: 100m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: {{ .Values.ratings.healthCheckPath }}
              port: {{ .Values.ratings.port }}
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: {{ .Values.ratings.healthCheckPath }}
              port: {{ .Values.ratings.port }}
              scheme: HTTP
      imagePullSecrets:
        - name: {{ .Values.ratings.imagePullSecrets }}
