image:
  tag: "4.4.1-debian-10-r12" # overrides default version value
auth:
  enabled: true
  rootPassword: "SECUREROOTPASS"
  username: "ratings"
  password: "SECUREPASS"
  database: "ratings"
initdbScriptsConfigMap: "bookinfo-prd-ratings-mongodb-initdb"
